stages:
    - build

build_docs:
    stage: build
    image: $CI_SPHINX_DOCKER:latest
    tags:
        - build_docs
    artifacts:
        when: always
        paths:
            # English version of documentation
            - docs/en/sphinx-warning-log.txt
            - docs/en/_build/html
            # Chinese version of documentation
            - docs/cn/sphinx-warning-log.txt
            - docs/cn/_build/html
        expire_in: 1 day
    script:
      - cd docs
      # make English version of documentation
      - cd en
      - make html
      - ../check_doc_warnings.sh
      # make Chinese version of documentation
      - cd ../cn
      - make html
      - ../check_doc_warnings.sh
  