stages:
    - pre_check
    - auto_trans
    - build_docs
    - deploy

include:
  - '.gitlab/ci/rules.yml'
  - '.gitlab/ci/pre_check.yml'
  - '.gitlab/ci/build_docs.yml'
  - '.gitlab/ci/deploy.yml'
  - '.gitlab/ci/auto_trans.yml'